name: "Graph build times to wiki page"
description: |
 "Builds and pushes docker image, while also generating a graph of build times
  for a given workflow and pushes it to project's wiki page"

inputs:
  github_personal_token:
    description: 'Github personal access token used to push graph to remote wiki repo'
    required: true

  # Docker image build/push related inputs
  docker_username:
    description: 'Username for dockerhub'
    required: true
  docker_password:
    description: 'Password for dockerhub'
    required: true
  docker_repository:
    description: 'Dockerhub repository name'
    required: true
  tag:
    description: 'Tag name for generated image'
    default: latest

  # Graph and badge related inputs
  last_build_time:
    description: 'Last build time. Format example 20m40s'
    required: true
  last_build_time_file:
    description: 'Full path to a file generated inside docker image'
    required: true
  build_times_filename:
    description: 'Filename where the previous build times are stored. File format should be CSV'
    default: 'build_times.csv'
  graph_filename:
    description: 'Filename for the generated graph that will be pushed to the wiki repo'
    default: 'graph.png'
  badge_filename:
    description: 'Filename for generated badge which displays most recent build time.File format should be SVG'
    default: 'build_status_badge.svg'
  badge_title:
    description: 'Name that will be displayed on the badge'
    default: ${{ github.repository }} build time
  badge_logo:
    description: 'Logo which will be displayed on the badge. For the list of logos see https://shields.io/'
  num_last_build:
    description: 'Number of last builds used for generating graph'
    default: '25'
  title:
    description: 'Title of the generated graph'
  x_label:
    description: 'X axis label'
    default: Run number
  y_label:
    description: 'Y axis label'
    default: Build time (min)
  graph_width:
    description: 'Graph width in inches'
    default: 6.4
  graph_height:
    description: 'Graph height in inches'
    default: 4.8
  commit_message:
    description: 'Commit message for wiki page'
    default: Push build time graph
  run_number:
    description: 'Run number of the current workflow'
    default: ${{github.run_number}}


runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book-open"
  color: "white"
