name: Linter

on:
  pull_request

jobs:
  check:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "*.py"
          use-pylint: true
          use-pycodestyle: false
          use-flake8: false
          use-black: true
          use-mypy: true
          use-isort: true
          extra-pylint-options: "--rcfile=setup.cfg --max-line-length=120 --max-locals=25"
          extra-mypy-options: "--ignore-missing-imports --show-error-codes"
          extra-isort-options: "--settings-file=setup.cfg"
